apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  labels:
    app: movies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies
      tier: frontend
  template:
    metadata:
      labels:
        app: movies
        tier: frontend
    spec:
      containers:
        - name: movies
          image: dineshtamang14/movies-website
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
          ports:
            - containerPort: 3000
          env:
            - name: TMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: movies-secret
                  key: api-key