apiVersion: v1
kind: Service
metadata:
  name: movies-svc
  labels:
    app: movies
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: movies
    tier: frontend
  ports:
    - port: 80
      targetPort: 3000
